spring:
  application:
    name: community-service
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_READ_URI}

  jwt:
    secret: ${JWT_SECRET}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true

cloud:
  aws:
    credentials:
      access-key: ${STORAGE_ACCESS_KEY}
      secret-key: ${STORAGE_SECRET_KEY}
    s3:
      bucket: ${BUCKET_NAME}
      endpoint: ${BUCKET_ENDPOINT}

sentry:
  dsn: ${SENTRY_REPOSITORY_DSN}
  environment: ${SENTRY_ENVIRONMENT}
  servername: ${SENTRY_SERVERNAME}
  repository-uri: ${SENTRY_REPOSITORY_URI}

logging:
  config: classpath:logback-spring.xml

server:
  port: 8082

feign:
  user:
    url: http://user-service:8080

slack:
  webhook-url: ${SLACK_WEBHOOK_URL}
