spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  jwt:
    secret: "secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate : DEBUG
            repository:
              query : DEBUG

    com:
      mongodb : DEBUG

feign:
  user:
    url: http://user-dummy

  match:
    url: http://match-dummy